### PR TITLE
Upgraded net-ldap module from 0.5.0 => 0.10.0

### PR DESCRIPTION
**Pull request by patelanuj28**
- To fix SSL issue I have upgraded net-ldap to 0.10.0 and retained 'keepalive' changes as it is. 
- Verified domain registration with LDAPS works

### CODE REVIEW

**Comment by smlsml** [comment]
Did you have to retain our keepalive changes? Does the default 0.10.0 not have support for that? Does 0.14.0? Can you check.

I'm hoping we can just go directly to 0.14.0 and delete this fork.

**Comment by smlsml** [comment]
If we do have to update this and keep our fork. We should also extract the keep-alive changes here and and submit them to the Net::LDAP upstream so hopefully they incorporate them.

**Comment by patelanuj28** [comment]
Nope, 0.10.0 doesn't have support of keepalive. We have to retain it for this fix.

**Comment by smlsml** [comment]
Boooooooo sad-face

**Comment by patelanuj28** [comment]
I'll submit pull-request to Net::LDAP 0.10.0 branch for keepalive changes.

**Comment by smlsml** [comment]
Awesome, you rock.

**Comment by smlsml** [comment]
Superseeded by 0.15.0 pull request, closing

**Pull request closed without merging**
